# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- trunk

pool:
  vmImage: ubuntu-18.04

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.7'
  displayName: 'Use Python 3.7'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m flake8 --exclude=venv,.git,__pycache__
  displayName: 'lint the source code'

- script: |
    python -m mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers --strict .
  displayName: 'validate types'

- script: |
    python -m coverage run -m unittest tests.main
  displayName: 'unittest and code coverage'

- script: |
    python -m coverage report --omit="venv/*,tests/*"
  displayName: 'generate code coverage report'



